# DRANET DeviceClasses — free5GC UPF
# DRANet driver name: dra.net

---
apiVersion: resource.k8s.io/v1beta1
kind: DeviceClass
metadata:
  name: net-ipvlan
spec:
  selectors:
    - cel:
        expression: "device.driver == 'dra.net'"
    - cel:
        expression: "device.attributes['dra.net'].ifName == 'n3br' || device.attributes['dra.net'].ifName == 'n4br'"
  config:
    - opaque:
        driver: dra.net
        parameters:
          interface:
            interfaceType: ipvlan
            mode: l2

---
apiVersion: resource.k8s.io/v1beta1
kind: DeviceClass
metadata:
  name: net-macvlan
spec:
  selectors:
    - cel:
        expression: "device.driver == 'dra.net'"
    - cel:
        expression: "device.attributes['dra.net'].ifName == 'n3br' || device.attributes['dra.net'].ifName == 'n4br'"
  config:
    - opaque:
        driver: dra.net
        parameters:
          interface:
            interfaceType: macvlan
            mode: bridge
