apiVersion: v1
kind: ConfigMap
metadata:
  name: smf2-configmap
  labels:
    app: free5gc
    nf: smf
    name: smf2
data:
  smfcfg.yaml: |
    info:
      version: 1.0.7
      description: SMF initial local configuration

    configuration:
      smfName: SMF2
      sbi:
        scheme: http
        registerIPv4: smf2-nsmf
        bindingIPv4: 0.0.0.0
        port: 8000
      serviceNameList:
        - nsmf-pdusession
        - nsmf-event-exposure
        - nsmf-oam
      snssaiInfos:
        - sNssai:
            sst: 1
            sd: 000002
          dnnInfos:
            - dnn: streaming
              dns:
                ipv4: 8.8.8.8
      plmnList:
        - mcc: "001"
          mnc: "01"
      locality: area1
      pfcp:
        listenAddr: 10.10.4.102
        externalAddr: 10.10.4.102
        nodeID: 10.10.4.102
        heartbeatInterval: 10s
      userplaneInformation:
        upNodes:
          gNB:
            type: AN
          UPF2:
            type: UPF
            nodeID: 10.10.4.2
            addr: 10.10.4.2
            sNssaiUpfInfos:
              - sNssai:
                  sst: 1
                  sd: 000002
                dnnUpfInfoList:
                  - dnn: streaming
                    pools:
                      - cidr: 10.2.0.0/16
            interfaces:
              - interfaceType: N3
                endpoints:
                  - 10.10.3.2
                networkInstances:
                  - streaming
        links:
          - A: gNB
            B: UPF2
      nrfUri: http://nrf-nnrf:8000
      t3591:
        enable: true
        expireTime: 16s
        maxRetryTimes: 3
      t3592:
        enable: true
        expireTime: 16s
        maxRetryTimes: 3

    logger:
      enable: true
      level: info
      reportCaller: false

  uerouting.yaml: |
    info:
      version: 1.0.7
      description: Routing information for UE
    ueRoutingInfo: # the list of UE routing information
      UE1: # Group Name
        members:
        - imsi-0010100000002 # Subscription Permanent Identifier of the UE
        topology: # Network topology for this group (Uplink: A->B, Downlink: B->A)
        # default path derived from this topology
        # node name should be consistent with smfcfg.yaml
          - A: gNB
            B: UPF2
        specificPath:
          - dest: 10.60.0.103/32 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
            path: [BranchingUPF, AnchorUPF2]
